### ISSUE TITLE
[PINNED] **[TODO]** list of broken commands 

### ISSUE THREAD

**Issue by fily-gif** [fily-gif/evry#6]
- [x] **/help** // <-- pagination (@mo4ki помоги)

- [x] /weather // <-- sunrise and sunset only

- [x] /pull // <-- pull specific hash, surely its not that hard :clueless:

~~- [ ] /roll // <-- rework soon, will be more suitable for DnD~~ <-- impossible because of /calc

### **bold** text - WIP

**Comment by fily-gif** [comment]
> /weather

okay so it fixed itself.

**Comment by fily-gif** [comment]
> /help

semi-fixed? idk, it works but i need to do something to not show that the button failed

**Comment by fily-gif** [comment]
> /pull

needs testing.

**Comment by fily-gif** [comment]
> /calc

no fucking way. thats actually crazy

**Comment by fily-gif** [comment]
> /cmd

wont fix.

**Comment by fily-gif** [comment]
> > /calc
> 
> no fucking way. thats actually crazy

nvm

**Comment by fily-gif** [comment]
> /help

wont fix, too much trouble +slash commands are available anyways
